# Generated by Django 4.2.17 on 2025-06-12 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_blogpost_likes_blogpost_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTravelPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_countries', models.JSONField(default=list, help_text='List of country codes the user prefers to visit')),
                ('preferred_activities', models.JSONField(blank=True, default=list, help_text="Types of activities the user enjoys (e.g., 'beach', 'hiking', 'city')")),
                ('preferred_climate', models.CharField(blank=True, help_text="User's climate preference (e.g., 'warm', 'cold', 'tropical')", max_length=50)),
                ('preferred_budget_range', models.CharField(blank=True, help_text="User's typical travel budget range (e.g., 'budget', 'mid-range', 'luxury')", max_length=20)),
                ('travel_style', models.JSONField(blank=True, default=dict, help_text="User's travel preferences like accommodation type, trip duration, etc.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Travel Preferences',
                'verbose_name_plural': 'User Travel Preferences',
            },
        ),
    ]
